### ISSUE TITLE
HTTP response code 401 when attempting to connect to JIRA

### ISSUE THREAD

**Issue by ProjectDent** [devondragon/jira-omnifocus#22]
_I've replaced my company's atlassian account with "mycompany"._

My `.jofsync.yaml` file is in the home directory, and looks like this:

```
jira:
  hostname: 'https://mycompany.atlassian.net'
  keychain: false
  username: 'andrew.hart'
  password: 'mypassword'
  filter:   'assignee = currentUser() AND status not in (Closed, Resolved)'
omnifocus:
  context:  'No Context'
  project:  'Work Project'
  flag:     true
```

Running `ruby jiraomnifocus.rb` in terminal, I get this error:

> jiraomnifocus.rb:88:in `block in get_issues': Unsuccessful HTTP response code 401 from mycompany.atlassian.net (StandardError)

Ruby version: ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
